yomim = [
    'הַיּוֹם <span class=bold>יוֹם אֶחָד</span> לָעֽוֹמֶר',
    'הַיּוֹם <span class=bold>שְׁנֵי יָמִים</span> לָעֽוֹמֶר',
    'הַיּוֹם <span class=bold>שְׁלשָׁה יָמִים</span> לָעֽוֹמֶר',
    'הַיּוֹם <span class=bold>אַרְבָּעָה יָמִים</span> לָעֽוֹמֶר',
    'הַיּוֹם <span class=bold>חֲמִשָּׁה יָמִים</span> לָעֽוֹמֶר',
    'הַיּוֹם <span class=bold>שִׁשָּׁה יָמִים</span> לָעֽוֹמֶר',
    'הַיּוֹם <span class=bold>שִׁבְעָה יָמִים</span> שֶׁהֵם <span class=bold>שָׁבֽוּעַ אֶחָד</span> לָעֽוֹמֶר',
    'הַיּוֹם <span class=bold>שְׁמוֹנָה יָמִים</span> שֶׁהֵם <span class=bold>שָׁבֽוּעַ אֶחָד</span> <span class=bold>וְ</span><span class=bold>יוֹם אֶחָד</span> לָעֽוֹמֶר',
    'הַיּוֹם <span class=bold>תִּשְׁעָה יָמִים</span> שֶׁהֵם <span class=bold>שָׁבֽוּעַ אֶחָד</span> <span class=bold>וּ</span><span class=bold>שְֿׁנֵי יָמִים</span> לָעֽוֹמֶר',
    'הַיּוֹם <span class=bold>עֲשָׂרָה יָמִים</span> שֶׁהֵם <span class=bold>שָׁבֽוּעַ אֶחָד</span> <span class=bold>וּ</span><span class=bold>שְֿׁלשָׁה יָמִים</span> לָעֽוֹמֶר',
    'הַיּוֹם <span class=bold>אַחַד עָשָׂר יוֹם</span> שֶׁהֵם <span class=bold>שָׁבֽוּעַ אֶחָד</span> <span class=bold>וְ</span><span class=bold>אַרְבָּעָה יָמִים</span> לָעֽוֹמֶר',
    'הַיּוֹם <span class=bold>שְׁנֵים עָשָׂר יוֹם</span> שֶׁהֵם <span class=bold>שָׁבֽוּעַ אֶחָד</span> <span class=bold>וַ</span><span class=bold>חֲמִשָּׁה יָמִים</span> לָעֽוֹמֶר',
    'הַיּוֹם <span class=bold>שְׁלשָׁה עָשָׂר יוֹם</span> שֶׁהֵם <span class=bold>שָׁבֽוּעַ אֶחָד</span> <span class=bold>וְ</span><span class=bold>שִׁשָּׁה יָמִים</span> לָעֽוֹמֶר',
    'הַיּוֹם <span class=bold>אַרְבָּעָה עָשָׂר יוֹם</span> שֶׁהֵם <span class=bold>שְׁנֵי שָׁבוּעוֹת</span> לָעֽוֹמֶר',
    'הַיּוֹם <span class=bold>חֲמִשָּׁה עָשָׂר יוֹם</span> שֶׁהֵם <span class=bold>שְׁנֵי שָׁבוּעוֹת</span> <span class=bold>וְ</span><span class=bold>יוֹם אֶחָד</span> לָעֽוֹמֶר',
    'הַיּוֹם <span class=bold>שִׁשָּׁה עָשָׂר יוֹם</span> שֶׁהֵם <span class=bold>שְׁנֵי שָׁבוּעוֹת</span> <span class=bold>וּ</span><span class=bold>שְֿׁנֵי יָמִים</span> לָעֽוֹמֶר',
    'הַיּוֹם <span class=bold>שִׁבְעָה עָשָׂר יוֹם</span> שֶׁהֵם <span class=bold>שְׁנֵי שָׁבוּעוֹת</span> <span class=bold>וּ</span><span class=bold>שְֿׁלשָׁה יָמִים</span> לָעֽוֹמֶר',
    'הַיּוֹם <span class=bold>שְׁמוֹנָה עָשָׂר יוֹם</span> שֶׁהֵם <span class=bold>שְׁנֵי שָׁבוּעוֹת</span> <span class=bold>וְ</span><span class=bold>אַרְבָּעָה יָמִים</span> לָעֽוֹמֶר',
    'הַיּוֹם <span class=bold>תִּשְׁעָה עָשָׂר יוֹם</span> שֶׁהֵם <span class=bold>שְׁנֵי שָׁבוּעוֹת</span> <span class=bold>וַ</span><span class=bold>חֲמִשָּׁה יָמִים</span> לָעֽוֹמֶר',
    'הַיּוֹם <span class=bold>עֶשְׂרִים יוֹם</span> שֶׁהֵם <span class=bold>שְׁנֵי שָׁבוּעוֹת</span> <span class=bold>וְ</span><span class=bold>שִׁשָּׁה יָמִים</span> לָעֽוֹמֶר',
    'הַיּוֹם <span class=bold>אֶחָד וְעֶשְׂרִים יוֹם</span> שֶׁהֵם <span class=bold>שְׁלשָׁה שָׁבוּעוֹת</span> לָעֽוֹמֶר',
    'הַיּוֹם <span class=bold>שְׁנַֽיִם וְעֶשְׂרִים יוֹם</span> שֶׁהֵם <span class=bold>שְׁלשָׁה שָׁבוּעוֹת</span> <span class=bold>וְ</span><span class=bold>יוֹם אֶחָד</span> לָעֽוֹמֶר',
    'הַיּוֹם <span class=bold>שְׁלשָׁה וְעֶשְׂרִים יוֹם</span> שֶׁהֵם <span class=bold>שְׁלשָׁה שָׁבוּעוֹת</span> <span class=bold>וּ</span><span class=bold>שְֿׁנֵי יָמִים</span> לָעֽוֹמֶר',
    'הַיּוֹם <span class=bold>אַרְבָּעָה וְעֶשְׂרִים יוֹם</span> שֶׁהֵם <span class=bold>שְׁלשָׁה שָׁבוּעוֹת</span> <span class=bold>וּ</span><span class=bold>שְֿׁלשָׁה יָמִים</span> לָעֽוֹמֶר',
    'הַיּוֹם <span class=bold>חֲמִשָּׁה וְעֶשְׂרִים יוֹם</span> שֶׁהֵם <span class=bold>שְׁלשָׁה שָׁבוּעוֹת</span> <span class=bold>וְ</span><span class=bold>אַרְבָּעָה יָמִים</span> לָעֽוֹמֶר',
    'הַיּוֹם <span class=bold>שִׁשָּׁה וְעֶשְׂרִים יוֹם</span> שֶׁהֵם <span class=bold>שְׁלשָׁה שָׁבוּעוֹת</span> <span class=bold>וַ</span><span class=bold>חֲמִשָּׁה יָמִים</span> לָעֽוֹמֶר',
    'הַיּוֹם <span class=bold>שִׁבְעָה וְעֶשְׂרִים יוֹם</span> שֶׁהֵם <span class=bold>שְׁלשָׁה שָׁבוּעוֹת</span> <span class=bold>וְ</span><span class=bold>שִׁשָּׁה יָמִים</span> לָעֽוֹמֶר',
    'הַיּוֹם <span class=bold>שְׁמוֹנָה וְעֶשְׂרִים יוֹם</span> שֶׁהֵם <span class=bold>אַרְבָּעָה שָׁבוּעוֹת</span> לָעֽוֹמֶר',
    'הַיּוֹם <span class=bold>תִּשְׁעָה וְעֶשְׂרִים יוֹם</span> שֶׁהֵם <span class=bold>אַרְבָּעָה שָׁבוּעוֹת</span> <span class=bold>וְ</span><span class=bold>יוֹם אֶחָד</span> לָעֽוֹמֶר',
    'הַיּוֹם <span class=bold>שְׁלשִׁים יוֹם</span> שֶׁהֵם <span class=bold>אַרְבָּעָה שָׁבוּעוֹת</span> <span class=bold>וּ</span><span class=bold>שְֿׁנֵי יָמִים</span> לָעֽוֹמֶר',
    'הַיּוֹם <span class=bold>אֶחָד וּשְֿׁלשִׁים יוֹם</span> שֶׁהֵם <span class=bold>אַרְבָּעָה שָׁבוּעוֹת</span> <span class=bold>וּ</span><span class=bold>שְֿׁלשָׁה יָמִים</span> לָעֽוֹמֶר',
    'הַיּוֹם <span class=bold>שְׁנַֽיִם וּשְֿׁלשִׁים יוֹם</span> שֶׁהֵם <span class=bold>אַרְבָּעָה שָׁבוּעוֹת</span> <span class=bold>וְ</span><span class=bold>אַרְבָּעָה יָמִים</span> לָעֽוֹמֶר',
    'הַיּוֹם <span class=bold>שְׁלשָׁה וּשְֿׁלשִׁים יוֹם</span> שֶׁהֵם <span class=bold>אַרְבָּעָה שָׁבוּעוֹת</span> <span class=bold>וַ</span><span class=bold>חֲמִשָּׁה יָמִים</span> לָעֽוֹמֶר',
    'הַיּוֹם <span class=bold>אַרְבָּעָה וּשְֿׁלשִׁים יוֹם</span> שֶׁהֵם <span class=bold>אַרְבָּעָה שָׁבוּעוֹת</span> <span class=bold>וְ</span><span class=bold>שִׁשָּׁה יָמִים</span> לָעֽוֹמֶר',
    'הַיּוֹם <span class=bold>חֲמִשָּׁה וּשְֿׁלשִׁים יוֹם</span> שֶׁהֵם <span class=bold>חֲמִשָּׁה שָׁבוּעוֹת</span> לָעֽוֹמֶר',
    'הַיּוֹם <span class=bold>שִׁשָּׁה וּשְֿׁלשִׁים יוֹם</span> שֶׁהֵם <span class=bold>חֲמִשָּׁה שָׁבוּעוֹת</span> <span class=bold>וְ</span><span class=bold>יוֹם אֶחָד</span> לָעֽוֹמֶר',
    'הַיּוֹם <span class=bold>שִׁבְעָה וּשְֿׁלשִׁים יוֹם</span> שֶׁהֵם <span class=bold>חֲמִשָּׁה שָׁבוּעוֹת</span> <span class=bold>וּ</span><span class=bold>שְֿׁנֵי יָמִים</span> לָעֽוֹמֶר',
    'הַיּוֹם <span class=bold>שְׁמוֹנָה וּשְֿׁלשִׁים יוֹם</span> שֶׁהֵם <span class=bold>חֲמִשָּׁה שָׁבוּעוֹת</span> <span class=bold>וּ</span><span class=bold>שְֿׁלשָׁה יָמִים</span> לָעֽוֹמֶר',
    'הַיּוֹם <span class=bold>תִּשְׁעָה וּשְֿׁלשִׁים יוֹם</span> שֶׁהֵם <span class=bold>חֲמִשָּׁה שָׁבוּעוֹת</span> <span class=bold>וְ</span><span class=bold>אַרְבָּעָה יָמִים</span> לָעֽוֹמֶר',
    'הַיּוֹם <span class=bold>אַרְבָּעִים יוֹם</span> שֶׁהֵם <span class=bold>חֲמִשָּׁה שָׁבוּעוֹת</span> <span class=bold>וַ</span><span class=bold>חֲמִשָּׁה יָמִים</span> לָעֽוֹמֶר',
    'הַיּוֹם <span class=bold>אֶחָד וְאַרְבָּעִים יוֹם</span> שֶׁהֵם <span class=bold>חֲמִשָּׁה שָׁבוּעוֹת</span> <span class=bold>וְ</span><span class=bold>שִׁשָּׁה יָמִים</span> לָעֽוֹמֶר',
    'הַיּוֹם <span class=bold>שְׁנַֽיִם וְאַרְבָּעִים יוֹם</span> שֶׁהֵם <span class=bold>שִׁשָּׁה שָׁבוּעוֹת</span> לָעֽוֹמֶר',
    'הַיּוֹם <span class=bold>שְׁלשָׁה וְאַרְבָּעִים יוֹם</span> שֶׁהֵם <span class=bold>שִׁשָּׁה שָׁבוּעוֹת</span> <span class=bold>וְ</span><span class=bold>יוֹם אֶחָד</span> לָעֽוֹמֶר',
    'הַיּוֹם <span class=bold>אַרְבָּעָה וְאַרְבָּעִים יוֹם</span> שֶׁהֵם <span class=bold>שִׁשָּׁה שָׁבוּעוֹת</span> <span class=bold>וּ</span><span class=bold>שְֿׁנֵי יָמִים</span> לָעֽוֹמֶר',
    'הַיּוֹם <span class=bold>חֲמִשָּׁה וְאַרְבָּעִים יוֹם</span> שֶׁהֵם <span class=bold>שִׁשָּׁה שָׁבוּעוֹת</span> <span class=bold>וּ</span><span class=bold>שְֿׁלשָׁה יָמִים</span> לָעֽוֹמֶר',
    'הַיּוֹם <span class=bold>שִׁשָּׁה וְאַרְבָּעִים יוֹם</span> שֶׁהֵם <span class=bold>שִׁשָּׁה שָׁבוּעוֹת</span> <span class=bold>וְ</span><span class=bold>אַרְבָּעָה יָמִים</span> לָעֽוֹמֶר',
    'הַיּוֹם <span class=bold>שִׁבְעָה וְאַרְבָּעִים יוֹם</span> שֶׁהֵם <span class=bold>שִׁשָּׁה שָׁבוּעוֹת</span> <span class=bold>וַ</span><span class=bold>חֲמִשָּׁה יָמִים</span> לָעֽוֹמֶר',
    'הַיּוֹם <span class=bold>שְׁמוֹנָה וְאַרְבָּעִים יוֹם</span> שֶׁהֵם <span class=bold>שִׁשָּׁה שָׁבוּעוֹת</span> <span class=bold>וְ</span><span class=bold>שִׁשָּׁה יָמִים</span> לָעֽוֹמֶר',
    'הַיּוֹם <span class=bold>תִּשְׁעָה וְאַרְבָּעִים יוֹם</span> שֶׁהֵם <span class=bold>שִׁבְעָה שָׁבוּעוֹת</span> לָעֽוֹמֶר'
]

def yom(day):
    return yomim[day]
